import os
homepage= 'home.html'
COOKIELABEL=['userID','customerNumber']

STATUSS = ["not logged in","logged in"]
SESSION_STATUS = STATUSS[0]
# PORTFOLIO DETAILS
PORTFOLIO_DETAIL_ID = 0
PORTFOLIO_DETAIL_PARENT_PORTFOLIO = 1
PORTFOLIO_DETAIL_COIN = 2
PORTFOLIO_DETAIL_PRICE = 3
PORTFOLIO_DETAIL_QTY = 4
